# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('telephone', models.BigIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
