# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=60)),
                ('press', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sum_quantity', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1', max_length=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Book')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User'),
        ),
    ]
