# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20160712_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sum_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
