# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.CharField(choices=[('\u542f\u7528', '\u542f\u7528'), ('\u7981\u7528', '\u7981\u7528')], default='\u542f\u7528', max_length=10, verbose_name='\u8bbe\u5907\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_spname',
            field=models.CharField(choices=[('\u4e2d\u56fd\u7535\u4fe1', '\u4e2d\u56fd\u7535\u4fe1'), ('\u4e2d\u56fd\u8054\u901a', '\u4e2d\u56fd\u8054\u901a'), ('\u4e2d\u56fd\u79fb\u52a8', '\u4e2d\u56fd\u79fb\u52a8'), ('\u4e2d\u56fd\u94c1\u901a', '\u4e2d\u56fd\u94c1\u901a'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='\u4e2d\u56fd\u8054\u901a', max_length=10, verbose_name='\u8fd0\u8425\u5546'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('\u603b\u90e8', '\u603b\u90e8'), ('\u5206\u90e8', '\u5206\u90e8')], default='\u603b\u90e8', max_length=50, verbose_name='\u8282\u70b9\u7c7b\u578b'),
        ),
    ]
