# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-23 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_auto_20171223_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_contacts',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u8054\u7cfb\u4eba'),
        ),
    ]
